codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: 70...100
  status:
    project:
      default:
        target: 70%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 50%
        threshold: 5%
        if_ci_failed: error

comment:
  layout: "header, diff, changes, components, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  unittests:
    paths:
      - src/

ignore:
  - "tests/"
  - "benches/"
  - "examples/"
